var i18n={
		'ru':{
			viewha_trn: '&#8592; [вьюха]',
			navMenu: 'Меню',
			close: 'Закрыть',
			settings: 'Настройка',
			lang: 'Язык интерфейса',
			stngSearch: 'Настройка поисковика',
			helpingView: 'Подсказки показывать',
			yes: 'Да',
			no: 'Нет',
			styleSite: 'Стиль сайта',
			light: 'светлый',
			dark: 'темный',
			styleMap: 'Стиль карты',
			whereToLook: 'Где искать',
			sites: 'сайты',
			images: 'картинки',
			news: 'новости',
			video: 'видео',
			map: 'карта',
			urlImgBack: 'URL картинки для фона',
			save: 'Сохранить',
			terms: 'Условие и правила',
			resViewTile: 'Результат поиска в виде "плитки"',
			resViewList: 'Результат поиска в виде "списка"',
			cnclSrcSite: 'Отменить поиск по сайту',
			entrYInqH: 'Сюда введите свой запрос',
			inpSrcQr: 'Поле ввода запроса для поиска',
			delSrcQr: 'Удалить поисковый запрос',
			srcButton: 'Кнопка поиска',
			goViewUp: 'Наверх к первому результату поиска',
			notFound: 'Ничего не найдено!',
			searchThisSite: 'Поиск по сайту:',
			searchThisSiteM: 'искать на этом сайте',
			searchMapSiteM: 'искать на карте',
			helpSrcYFocusY: 'нажмите клавишу "Enter &#x23ce;" или синюю кнопку со стрелкой ">", для поиска по запросу',
			helpSrcYFocusN: 'нажмите синюю кнопку со стрелкой ">", для поиска по запросу',
			helpSrcNFocusY1: '(1) - сформулируйте свой запрос и введите сюда',
			helpSrcNFocusY2: '(2) - нажмите синюю кнопку со стрелкой ">" для поиска по запросу или клавишу "Enter &#x23ce;"',
			helpSrcNFocusN: 'нажмите на строку поиска и введите сюда свой запрос',
			otherSrcEng: 'В других поисковиках:'
		},
		'en':{
			viewha_trn: '&#8592; [vjuːha]',
			navMenu: 'Menu',
			close: 'Close',
			settings: 'Settings',
			lang: 'Language',
			stngSearch: 'Setting up a search engine',
			helpingView: 'Tips show',
			yes: 'Yes',
			no: 'No',
			styleSite: 'Style site',
			light: 'light',
			dark: 'dark',
			styleMap: 'Style map',
			whereToLook: 'Where to look',
			sites: 'sites',
			images: 'images',
			news: 'news',
			video: 'video',
			map: 'map',
			urlImgBack: 'Image URL for the background',
			save: 'Save',
			terms: 'Terms and Rules',
			resViewTile: 'Search results in the form of a "tile"',
			resViewList: 'Search results in the form of a "list"',
			cnclSrcSite: 'Cancel Search Site',
			entrYInqH: 'Enter your inquiry here',
			inpSrcQr: 'The input field for the search query',
			delSrcQr: 'To delete a search query',
			srcButton: 'Search button',
			goViewUp: 'Up to the first search result',
			notFound: 'No Results Were Found!',
			searchThisSite: 'Search this site:',
			searchThisSiteM: 'search this site',
			searchMapSiteM: 'search on the map',
			helpSrcYFocusY: 'press "Enter &#x23ce;" or the blue arrow button ">" to search for on request',
			helpSrcYFocusN: 'click the blue arrow button ">" to search for on request',
			helpSrcNFocusY1: '(1) - specify your request and enter here',
			helpSrcNFocusY2: '(2) - press the blue arrow button ">" to search for on-demand, or press "Enter &#x23ce;"',
			helpSrcNFocusN: 'click on the search bar and enter your query here',
			otherSrcEng: 'In other search engines:'
		}
	};